CREATE TABLE `users` (
                         `id` mediumint(8) unsigned NOT NULL auto_increment,
                         `name` varchar(255) default NULL,
                         `surname` varchar(255) default NULL,
                         `mail` varchar(255) default NULL,
                         `country` varchar(100) default NULL,
                         PRIMARY KEY (`id`)
) AUTO_INCREMENT=1;

INSERT INTO `users` (`name`,`surname`,`mail`,`country`) VALUES ("Samuel","Hamilton","ornare@sitametante.co.uk","Bahrain"),("Porter","Faith","metus.urna@lacus.net","Denmark"),("Harlan","Hollee","vel@feugiat.com","Bouvet Island"),("Duncan","April","dolor.nonummy.ac@pedeNuncsed.edu","Slovakia"),("Robin","Hilda","pellentesque.eget@Duis.co.uk","Sao Tome and Principe"),("Tobias","Kendall","mus@tristiquesenectus.com","Tokelau"),("Hu","Caldwell","porta.elit@turpisvitaepurus.net","Jersey"),("Keegan","Simone","commodo.hendrerit.Donec@liberoProinmi.org","Guam"),("Wanda","Carla","malesuada.fames.ac@odiovelest.com","Gambia"),("Veda","Shelley","at@nonmassanon.com","Niue");
INSERT INTO `users` (`name`,`surname`,`mail`,`country`) VALUES ("Hadley","Carly","turpis.Aliquam@doloregestasrhoncus.com","Saudi Arabia"),("Quincy","Suki","ornare@accumsanlaoreetipsum.co.uk","Singapore"),("Joseph","Brooke","Proin@NullaaliquetProin.net","Bangladesh"),("Beau","Regan","molestie.sodales@malesuadavelvenenatis.com","New Caledonia"),("Briar","Olympia","auctor@elit.org","Mali"),("Cameron","Bruce","sem.Pellentesque@nuncQuisque.com","Estonia"),("Avram","Denise","enim@ullamcorpernisl.net","American Samoa"),("Lareina","Ella","turpis@ante.co.uk","Mexico"),("Hannah","Troy","et.eros.Proin@eget.co.uk","Suriname"),("Joan","Dara","mollis@Nuncullamcorper.net","Viet Nam");
INSERT INTO `users` (`name`,`surname`,`mail`,`country`) VALUES ("Howard","Maile","rutrum@euarcuMorbi.ca","Cape Verde"),("Fleur","Virginia","lorem.vehicula.et@facilisismagnatellus.ca","Turkmenistan"),("Chandler","Darius","non.cursus.non@Praesent.ca","Peru"),("Alexandra","Wylie","nunc.ullamcorper.eu@dignissimtemporarcu.net","Bhutan"),("Jakeem","Lara","dolor@consequatdolor.co.uk","Suriname"),("Cailin","Kameko","a@acsem.co.uk","Rwanda"),("Francis","Sara","at@MorbimetusVivamus.net","Nauru"),("Evelyn","Malcolm","Duis@adipiscingelit.edu","Eritrea"),("Caleb","Sharon","Aenean.gravida@tempusrisus.com","Azerbaijan"),("Plato","Alika","mi.pede@Craseu.net","Kiribati");
INSERT INTO `users` (`name`,`surname`,`mail`,`country`) VALUES ("Miriam","Kessie","semper.egestas.urna@sapienAeneanmassa.co.uk","Burundi"),("Sydney","Rebecca","dolor@tempordiam.ca","Venezuela"),("Noah","Lucy","tellus.Phasellus.elit@vitae.edu","Paraguay"),("McKenzie","Francis","aliquet.molestie@id.ca","Liberia"),("Charissa","Dustin","vestibulum.Mauris@ultricies.co.uk","Burundi"),("Ronan","Sylvia","amet.dapibus.id@tortor.net","Uruguay"),("Kylynn","Tobias","ultricies@Maurismagna.org","Zambia"),("Branden","Abdul","libero.est.congue@sedpedenec.com","Turkmenistan"),("Asher","Shea","ac@Donecegestas.net","Honduras"),("Lavinia","Imelda","velit@nonenimcommodo.edu","Tokelau");
INSERT INTO `users` (`name`,`surname`,`mail`,`country`) VALUES ("Ezra","Ashton","Phasellus@neque.net","Cocos (Keeling) Islands"),("Lana","Faith","in.molestie.tortor@metus.co.uk","Kyrgyzstan"),("Madeson","Deanna","erat.Sed.nunc@est.co.uk","American Samoa"),("Frances","Karina","ante.ipsum@augueidante.org","Ecuador"),("Sandra","Lionel","purus@Etiamvestibulum.com","Niue"),("Ariel","Kiayada","at.fringilla.purus@feugiat.ca","Antarctica"),("Sara","April","Nulla@cursusaenim.net","Benin"),("Daryl","Yardley","diam.lorem.auctor@Nulla.net","Benin"),("Doris","Orlando","ultricies.ornare@enim.ca","Romania"),("Jenette","Garrison","erat@velitduisemper.edu","Cambodia");
INSERT INTO `users` (`name`,`surname`,`mail`,`country`) VALUES ("Chancellor","Mary","penatibus@necligula.edu","Kyrgyzstan"),("Mara","Aileen","rhoncus.Proin@necenimNunc.ca","Anguilla"),("Zoe","Noelani","Cras.lorem@orciUt.co.uk","Martinique"),("Bell","Rogan","faucibus.leo.in@Nunc.com","Bolivia"),("Thane","Timon","tristique.pharetra.Quisque@telluslorem.edu","Montserrat"),("Madaline","Dexter","pellentesque.Sed@vitae.edu","Bahrain"),("Hilel","Sydnee","ornare@nullaInteger.edu","Egypt"),("Chadwick","Martha","et.pede.Nunc@duisemperet.net","Northern Mariana Islands"),("Norman","Ginger","nulla@eutellus.edu","Luxembourg"),("Maris","Kimberly","ut@Etiamvestibulummassa.ca","Senegal");
INSERT INTO `users` (`name`,`surname`,`mail`,`country`) VALUES ("Tashya","Aladdin","nulla.Cras.eu@ultricesposuere.net","Monaco"),("Yetta","Carlos","nec.ante.Maecenas@aliquamiaculis.ca","Burkina Faso"),("Katelyn","Reuben","natoque.penatibus.et@semmollis.net","Falkland Islands"),("Garrison","Jane","lorem.sit.amet@suscipitest.edu","Kazakhstan"),("Amelia","Vivian","libero.Donec@eleifendnunc.ca","Belarus"),("Kelsie","Leonard","lobortis@tempor.org","Virgin Islands, United States"),("Flynn","Lester","amet.risus.Donec@arcuAliquam.co.uk","French Southern Territories"),("Althea","Forrest","ut@sagittisNullamvitae.org","Palau"),("Axel","Avram","magna@lacusMauris.net","Saudi Arabia"),("Kaitlin","Arsenio","feugiat@aliquetmagnaa.com","Moldova");
INSERT INTO `users` (`name`,`surname`,`mail`,`country`) VALUES ("Jordan","Dahlia","dolor.tempus@Cras.edu","Montenegro"),("Uta","Violet","vel.lectus@dolor.net","Denmark"),("Cassady","Gil","mi@erat.net","Bulgaria"),("Emerald","Claudia","ornare.egestas@loremipsumsodales.edu","Nepal"),("Trevor","Ebony","Vestibulum.ante.ipsum@dictummagnaUt.ca","Ecuador"),("Mark","Alma","tincidunt.adipiscing@ipsumdolor.net","Tuvalu"),("Ray","Luke","lectus.ante@mieleifendegestas.net","Antigua and Barbuda"),("Branden","Blaine","ante.ipsum@velpede.edu","Viet Nam"),("Meredith","Phoebe","ut.eros.non@eratin.ca","Tokelau"),("Kelly","Tamara","neque@Morbiquis.org","Christmas Island");
INSERT INTO `users` (`name`,`surname`,`mail`,`country`) VALUES ("Yael","Maxwell","Nunc@Cras.ca","Netherlands"),("Nevada","Thor","lorem@mattis.edu","Swaziland"),("Chandler","Addison","eu.dui.Cum@odioEtiamligula.net","Korea, North"),("Jolie","Colleen","erat.Sed@Morbiquis.co.uk","Maldives"),("Justine","Elijah","sapien.imperdiet@semsemper.net","Aruba"),("Adrian","Kimberley","dui@Nullamscelerisqueneque.co.uk","China"),("Meredith","Minerva","vitae@Integertincidunt.co.uk","Sudan"),("Tasha","Boris","nonummy.ultricies.ornare@tellus.org","Luxembourg"),("Denise","Gary","Suspendisse@pulvinararcu.co.uk","Bolivia"),("Amy","Tanner","at.lacus.Quisque@Phasellusin.org","Uruguay");
INSERT INTO `users` (`name`,`surname`,`mail`,`country`) VALUES ("Ocean","Melvin","non.massa@interdumSed.net","Israel"),("Keith","Rahim","non@laciniamattis.net","Portugal"),("Kaden","Bruce","diam@mollislectuspede.ca","American Samoa"),("Nyssa","Laith","mollis@Pellentesqueultricies.co.uk","Mexico"),("Ariana","Vernon","a@acrisusMorbi.com","Jordan"),("Ferdinand","Laurel","augue@egetipsum.org","French Southern Territories"),("Shafira","Raymond","felis.adipiscing.fringilla@Praesentluctus.edu","Oman"),("Mary","Lana","arcu.Curabitur@arcuVestibulumut.org","Liechtenstein"),("Hayes","Avye","urna@bibendumsed.edu","Sri Lanka"),("Boris","Maite","Nulla.facilisis.Suspendisse@ut.edu","Kyrgyzstan");
